spring:
  datasource:
    url: jdbc:postgresql://db:5432/walletdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml